# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'adopt'
        server-id: central
        server-username: CENTRAL_USERNAME
        server-password: CENTRAL_TOKEN
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
    - name: Build with Maven
      run: mvn -B compile --file pom.xml

    - name: Test with Maven
      run: mvn -B test --file pom.xml
      
    - name: Submit code coverage
      run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_SECRET }}

    - name: Publish to Apache Maven Central
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      run: cat ~/.m2/settings.xml && mvn -DskipTests deploy -Dgpg.passphrase=${{ secrets.MAVEN_GPG_PASSPHRASE }}
      env:
        CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
        CENTRAL_TOKEN: ${{ secrets.CENTRAL_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
    
